---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: distro-image
    image: ${MOLECULE_DISTRO:-ubuntu:bionic}

provisioner:
  name: ansible
  env:
    AWSCLI_VERSION: "2.2.15"

verifier:
  name: ansible
