- name: Verify
  hosts: all
  tasks:
  
  - name: Check aws version
    command: "aws --version"
    ignore_errors: yes
    register: awscli_current_version

  - name: Ensure aws is not installed
    assert:
      that:
        - awscli_current_version.rc != 0
