---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  tags:
    - update-cache
    - install

- name: Install dependencies
  apt:
    name: "{{ dependencies_packages }}"
    state: present
    force: true
    update_cache: yes
  register: package_ok
  retries: "{{ global_downloads_retries }}"
  delay: "{{ global_downloads_delay }}"
  until: package_ok is success
  tags:
    - install
    - install-dependency

- name: Check current aws version.
  command: "aws --version"
  register: awscli_current_version
  changed_when: awscli_current_version.rc != 0 or (awscli_version != "" and awscli_version not in awscli_current_version.stdout)
  failed_when: false
  tags:
    - install
    - check-current-version

- name: Download archive # noqa no-handler
  get_url:
    url: "{{ awscli_download_url }}"
    dest: "{{ temp_folder }}/awscliv2.zip"
    mode: '0440'
  register: download_archive
  retries: "{{ global_downloads_retries }}"
  delay: "{{ global_downloads_delay }}"
  until: download_archive is success
  when: awscli_current_version.changed
  tags:
    - install
    - download-archive

- name: Unarchive Installer # noqa no-handler
  unarchive:
    src: "{{ temp_folder }}/awscliv2.zip"
    dest: "{{ temp_folder }}/"
    remote_src: yes
  register: unarchive_installer
  when: download_archive.changed    
  tags:
    - install
    - unarchive-installer

- name: Install AWS-CLI # noqa no-handler
  command: "{{ temp_folder }}/aws/install {{ '--update' if awscli_current_version.rc == 0 else ''}}"
  when: unarchive_installer.changed    
  tags:
    - install
    - install-cli

- name: Cleanup Archive
  file:
    path: "{{ temp_folder }}/awscliv2.zip"
    state: absent
  tags:
    - install
    - clean

- name: Cleanup Install
  file:
    path: "{{ temp_folder }}/aws"
    state: absent
  tags:
    - install
    - clean